public class checkDatatypes {
   public void methodBoolean(){
    boolean checkBoolean = true;
    system.debug(checkBoolean);
   }

   public void methodInteger(){
    integer varFirst = 1;
    integer varSecond =2;
    system.debug(varFirst);
    system.debug(varSecond);

   }
   public void stringMethod(){
    string varName1 = 'Ali';
    string varName2 = 'Veli';
    system.debug(varName1);
    system.debug(varName2);
   }
}
