public class Primitivedata_Assigment {
    public void PrimitiveDataMethod(){
        Id id1= '0018Z00002eznwIQAQ';
        system.debug('Id is = ' + id1);

        String str1 = 'the following Id belongs to Accounts';
        system.debug('String is = ' + str1);

        Boolean bln1 = true;
        system.debug('Boolean is = ' + bln1 +  ' '+ ' the following Id  belongs to Accounts ' + id1); 


        

    }
}
