public class PrimitiveDataTypeDemo3 {
    public void print1(){
       Id id1 = '0018Z00002eznwIQAQ';
       system.debug('print id = ' + id1);
       
     //Object --> Object i a parent class to all primitive data types, sObjects, custom classes and everything in apex


       Object obj1 = 'This is a string ';
       Object obj2 = 15;
       Object obj33454 = '0015i00000BFSCtAAP';
       Object obj4 = true;

       system.debug('obj1 = '+ obj1);
       system.debug('obj2 = '+ obj2);
       system.debug('obj33454 = ' + obj33454);
       system.debug('obj4 = ' + obj4);
       
    }
}
