public class SalesforceDeveloper {
    public void myFirstCode(){
       string myFavCity = 'Erzurum';
       string myFavMovie = 'Hukumet Kadin';
       string myFavSeason = 'Summer';
       
       System.debug('Benim sevdigim sehir ' + myFavCity);
       System.debug('Severek seyrettigim film ise ' + myFavMovie);
       System.debug('Sevdigim mevsim ise ' +myFavSeason);

    }

    public void myFavorites(){
        string myCity = 'Indiana';
        integer myFavNum = 3;

        System.debug('Yasadigim sehir ' + myCity);
        System.debug('Sevdigim numara ' + myFavNum);
        
    }
}
